# Enable/disable swapping item to armor stand
Armor_stand_swap: true
# Enable/disable swapping item to armor stand
Main_hand_swap: true
# Enable/Disable swapping item to item frames
Item_frame_swap: true
#sound to play on swap
Sound: ITEM_ARMOR_EQUIP_TURTLE