# Enable/disable swapping item to armor stand
Armor_stand_swap: true
# Enable/disable swapping item to armor stand
Main_hand_swap: true
# Enable/Disable swapping item to item frames
Item_frame_swap: true
#sound to play on swap
Sound: ITEM_ARMOR_EQUIP_TURTLE
#----------------------------------------------------------------------------------------------------------------
#
#				                 Language
#
#----------------------------------------------------------------------------------------------------------------
# prefix
Prefix: "&bArmorSwap &7-"
# when player runs /armorswap
Enable: "&bArmor swap is now enabled for you"
Disable: "&bArmor swap is now disabled for you"
# on wrong usage
usageError: "&bUse &7/armorswap&b to enable armor swap"