name: ArmorSwap
version: '${project.version}'
main: com.toonystank.armorswap.ArmorSwap
api-version: 1.17
authors: [ Edward ]
description: Simple Armorswap plugin. Swap armor by right clicking (This is a test project)
website: https://taggernation.com
commands:
  Armor:
    description: Enable or disable armor swapping
    usage: /<command>
  Head:
    description: Swap item to your head
    usage: /<command>
  armorswapreload:
    description: reload Armorswap plugin
    usage: /<command>
