package com.toonystank.armorswap.utils;

public enum DataType {

    ARMOR_STAND_SWAP,
    ITEM_FRAME_SWAP,
    MAIN_HAND_SWAP,
    PLAYER_BOOTS,
    PLAYER_LEGGINGS,
    PLAYER_CHEST_PLATE,
    PLAYER_HELMET,
    STAND_BOOTS,
    STAND_LEGGINGS,
    STAND_CHEST_PLATE,
    STAND_HELMET,
    PLAYER_MAIN_HAND,
    PLAYER_OFF_HAND,
    STAND_MAIN_HAND,
    STAND_OFF_HAND
}